import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios"
export const getStaticProps = async () => {


  
  const res = await axios.get('http://localhost:5000/tracks')
  const data = await res.data
  return {
    props: { ninjas: data }
  }
}
export default function Home({ninjas}) {
  
    const addToCard = async() => {
      const response = await axios('http://localhost:5000/tracks', {
        method:'POST',
        
        data: {imageUrl:'123'}
      }).catch(e => console.log(e))
    }
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {ninjas.map(ninja => (
        <div key={ninja.id} onClick={addToCard}>
          {ninja.imageUrl}
        </div>
      ))}
      
    </div>
  )
}
